image: python:3.11

stages:
  - test
  - build
  - deploy

variables:
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

test:
  stage: test
  script:
    - cd backend
    - pip install -r requirements.txt
    - python -m pytest

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_IMAGE ./backend
    - docker push $DOCKER_IMAGE

deploy:
  stage: deploy
  script:
    - helm upgrade --install podcast-player ./helm/podcast-player
  only:
    - main
