version: "3.8"

services:
  frontend:
    container_name: frontend
    hostname: frontend
    working_dir: /app
    tty: true
    stdin_open: true
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend/app:/app
    ports:
      - "4321:4321"
    environment:
      - NODE_ENV=development
    entrypoint: ["sh", "-c", "npm install && npm run dev"]

  backend:
    container_name: backend
    hostname: backend
    working_dir: /app/src
    tty: true
    stdin_open: true
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend/app:/app
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - PYTHONPATH=/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
