"""Add separate download and transcription status with available languages

Revision ID: d5576bce7abd
Revises: 
Create Date: 2025-06-22 19:45:04.237039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5576bce7abd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_files', sa.Column('download_status', sa.String(length=50), nullable=True))
    op.add_column('audio_files', sa.Column('transcription_status', sa.String(length=50), nullable=True))
    op.add_column('audio_files', sa.Column('available_languages', sa.JSON(), nullable=True))
    op.drop_index(op.f('idx_audio_files_episode'), table_name='audio_files')
    op.drop_index(op.f('idx_audio_files_series'), table_name='audio_files')
    op.create_index(op.f('ix_audio_files_id'), 'audio_files', ['id'], unique=False)
    op.drop_column('audio_files', 'status')
    op.drop_index(op.f('idx_transcriptions_audio_file'), table_name='transcriptions')
    op.drop_index(op.f('idx_transcriptions_content_type'), table_name='transcriptions')
    op.drop_index(op.f('idx_transcriptions_language'), table_name='transcriptions')
    op.drop_index(op.f('idx_transcriptions_time_range'), table_name='transcriptions')
    op.create_index(op.f('ix_transcriptions_id'), 'transcriptions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcriptions_id'), table_name='transcriptions')
    op.create_index(op.f('idx_transcriptions_time_range'), 'transcriptions', ['start_time_seconds', 'end_time_seconds'], unique=False)
    op.create_index(op.f('idx_transcriptions_language'), 'transcriptions', ['language'], unique=False)
    op.create_index(op.f('idx_transcriptions_content_type'), 'transcriptions', ['content_type'], unique=False)
    op.create_index(op.f('idx_transcriptions_audio_file'), 'transcriptions', ['audio_file_id'], unique=False)
    op.add_column('audio_files', sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'not_downloaded'::character varying"), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_audio_files_id'), table_name='audio_files')
    op.create_index(op.f('idx_audio_files_series'), 'audio_files', ['series_name'], unique=False)
    op.create_index(op.f('idx_audio_files_episode'), 'audio_files', ['episode_number'], unique=False)
    op.drop_column('audio_files', 'available_languages')
    op.drop_column('audio_files', 'transcription_status')
    op.drop_column('audio_files', 'download_status')
    # ### end Alembic commands ### 